- name: Install Docker and Docker Compose
  hosts: ejercicio2
  become: yes
  vars_files:
    - vars/variables.yaml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove existing Docker
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker.io
        - docker-compose

    - name: Install Docker
      apt:
        name: "{{ docker_package }}"
        state: present

    - name: Install Docker Compose
      apt:
        name: "{{ docker_compose_package }}"
        state: present

    - name: Ensure Docker service is running
      service:
        name: "{{ docker_service }}"
        state: started
        enabled: yes