- name: Install Docker and Docker Compose
  hosts: ejercicio2
  become: yes
  vars_files:
    - vars/variables.yaml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Desistalamos Docker existentes
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker.io
        - docker-compose

    - name: Instalamos Docker
      apt:
        name: docker.io
        state: present

    - name: Instalamos Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Empenzamos el servicio de Docker
      service:
        name: docker.service
        state: started
        enabled: yes